python SR.py dd/laser_hole
python PQFT.py dd/laser_hole
python PQFT_m.py dd/laser_hole
python SR.py dd/afvi
python PQFT.py dd/afvi
python PQFT_m.py dd/afvi
python SR.py mecaro
python PQFT.py mecaro
python PQFT_m.py mecaro
python SR.py pocons
python PQFT.py pocons
python PQFT_m.py pocons
python SR.py sse/aoi
python PQFT.py sse/aoi
python PQFT_m.py sse/aoi
python SR.py sse/xray
python PQFT.py sse/xray
python PQFT_m.py sse/xray